### ISSUE TITLE
RouterOS update

### ISSUE THREAD

**Issue by og900aero** [DinoTools/monitoring-check_routeros#32]
Would it be possible to somehow request whether there is an update for RouterOS?

**Comment by og900aero** [comment]
I check this: /system/package/update/check-for-updates

**Comment by phibos** [comment]
Version 0.6 has just been released and I think version 0.7 will be released in a few days. Than I will have a look at this feature again.

**Comment by phibos** [comment]
The feature has been merged into the main branch and will be in the next release.
