### ISSUE TITLE
Check disk usage

### ISSUE THREAD

**Issue by Virsacer** [DinoTools/monitoring-check_routeros#62]
Hi, would it be possible to add a check for disk usage?

Preferably with output in this format:

    OK 48% 54.5MB/113.2MB|used=57147392B;94959042;106828922;0;118698803

I am experimenting with containers on a device with no external storage, so this would be great.
Thanks!

**Comment by phibos** [comment]
I think this is a good idea. We can get the information from

```
> /system/resource/print 
[...]
           free-hdd-space: 198.3MiB
          total-hdd-space: 216.5MiB
[...]
```

**Comment by phibos** [comment]
The disk check has been added for the next 0.10.0 release and is currently in the main branch.
