### ISSUE TITLE
TimeoutError: _ssl.c:990: The handshake operation timed out

### ISSUE THREAD

**Issue by Virsacer** [DinoTools/monitoring-check_routeros#70]
Hi,

I often get the error `TimeoutError: _ssl.c:990: The handshake operation timed out`
How can I set the timeout?

Thanks!

**Comment by phibos** [comment]
An cli option has been added to set the timeout value. The change will be merged into the main branch feel free to test or have a look at the PR #81 .

What timeout value solve your issues?

**Comment by Virsacer** [comment]
I solved the issue by writing my own check-script

**Comment by phibos** [comment]
Thanks for your feedback. I have closed the issue.
