### ISSUE TITLE
Required python version should be 3.8

### ISSUE THREAD

**Issue by jon4hz** [DinoTools/monitoring-check_routeros#88]
Hi,
I noticed that the required python version is stated as 3.6. However you are using `re.Pattern` in some type annotations (e.g. [here](https://github.com/DinoTools/monitoring-check_routeros/blob/06730635f0590873f15bde419ec1c185fd206d40/routeros_check/check/system_cpu.py#L38)) and that class was introduced in python 3.8.

**Comment by phibos** [comment]
Thanks for reporting the issue. It will be fixed in the next release.
